import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.chart import BarChart, PieChart, Reference
from openpyxl.formatting.rule import CellIsRule, ColorScaleRule
from openpyxl.comments import Comment

import datetime

RAW_CSV = r"C:\Users\manas\Downloads\MM_CRM_Scripts\serviceFlow_raw_data.csv"
POC_CSV = r"C:\Users\manas\Downloads\MM_CRM_Scripts\poc_leaderboard.csv"
POC_TODAY_CSV = r"C:\Users\manas\Downloads\MM_CRM_Scripts\poc_leaderboard_today.csv"
QW_CSV = r"C:\Users\manas\Downloads\MM_CRM_Scripts\queue_waiting.csv"
ORPHANED_CSV = r"C:\Users\manas\Downloads\MM_CRM_Scripts\orphaned_cases.csv"
OUT_XLSX = r"C:\Users\manas\Downloads\MM_CRM_Scripts\Queue_Flow_Data_Analysis.xlsx"

df = pd.read_csv(RAW_CSV, dtype=str, keep_default_na=False)
n_rows = len(df)
last_row = n_rows + 1  # header is row 1

poc_df = pd.read_csv(POC_CSV, dtype=str, keep_default_na=False)
poc_last_row = len(poc_df) + 1
print(f"Loaded {len(poc_df)} POC leaderboard rows")

poc_today_df = pd.read_csv(POC_TODAY_CSV, dtype=str, keep_default_na=False)
print(f"Loaded {len(poc_today_df)} POC leaderboard rows (today)")

qw_df = pd.read_csv(QW_CSV, dtype=str, keep_default_na=False)
qw_totals = {r["role"]: (int(r["available"]), int(r["waiting"])) for _, r in qw_df[qw_df["bucket"] == "TOTAL"].iterrows()}
print(f"Loaded queue-waiting snapshot: {qw_totals}")

orphaned_df = pd.read_csv(ORPHANED_CSV, dtype=str, keep_default_na=False)
print(f"Loaded {len(orphaned_df)} orphaned-case alerts")

BUILD_TIME_STR = datetime.datetime.now().strftime("%d %b %Y, %I:%M %p")
print(f"Loaded {n_rows} rows")

FONT = "Arial"
navy = "1B2A2E"
teal = "1F6F63"
teal_light = "DCEEE9"
grey_light = "F4F6F5"
white = "FFFFFF"

def style_header(ws, row=1, ncols=None):
    ncols = ncols or ws.max_column
    for c in range(1, ncols + 1):
        cell = ws.cell(row=row, column=c)
        cell.font = Font(name=FONT, bold=True, color=white, size=10)
        cell.fill = PatternFill("solid", fgColor=teal)
        cell.alignment = Alignment(vertical="center", wrap_text=True)
        cell.border = Border(bottom=Side(style="thin", color=navy))

def autosize(ws, widths=None):
    for i, col in enumerate(ws.columns, start=1):
        letter = get_column_letter(i)
        if widths and letter in widths:
            ws.column_dimensions[letter].width = widths[letter]
            continue
        maxlen = 0
        for cell in col:
            if cell.value is not None:
                maxlen = max(maxlen, len(str(cell.value)))
        ws.column_dimensions[letter].width = min(max(maxlen + 2, 9), 32)

wb = Workbook()

# ============================================================= RAW DATA
ws = wb.active
ws.title = "Raw Data"

for j, colname in enumerate(df.columns, start=1):
    ws.cell(row=1, column=j, value=colname)

numeric_cols = {"serviceAmount", "amountPaid", "reAppliedCount", "pauseNoteCount",
                 "notConnectedRnrNoteCount", "stageTransitionNoteCount", "tatOverdueTaskCount",
                 "endToEndTatDays", "activePipelineAgingDays", "inFlightAgingDays"}

for i, row in enumerate(df.itertuples(index=False), start=2):
    for j, (colname, val) in enumerate(zip(df.columns, row), start=1):
        if colname in numeric_cols and val != "":
            try:
                val = float(val)
                if val == int(val):
                    val = int(val)
            except ValueError:
                pass
        ws.cell(row=i, column=j, value=val)
        ws.cell(row=i, column=j).font = Font(name=FONT, size=9)

style_header(ws)
ws.freeze_panes = "A2"

last_col_letter = get_column_letter(len(df.columns))
tab = Table(displayName="RawData", ref=f"A1:{last_col_letter}{last_row}")
tab.tableStyleInfo = TableStyleInfo(name="TableStyleMedium2", showRowStripes=True)
ws.add_table(tab)

narrow = {"A": 11, "B": 16, "C": 20, "D": 18, "E": 12, "F": 12, "G": 10, "H": 11, "I": 12, "J": 18,
          "K": 12, "L": 12, "M": 10, "N": 12, "O": 9, "P": 10, "Q": 10, "R": 12, "S": 9,
          "T": 12, "U": 11, "V": 8, "W": 12, "X": 11, "Y": 9, "Z": 9, "AA": 10, "AB": 9,
          "AC": 9, "AD": 9, "AE": 9, "AF": 9, "AG": 9, "AH": 11, "AI": 11, "AJ": 9}
autosize(ws, narrow)

note = ws.cell(row=1, column=1)
note.comment = Comment(
    "Source: live read-only query against Firestore vaultServices, filtered to serviceFlow == \"queue\". "
    "1,010 documents as of 1 Sep 2026. Generated by export_serviceFlow_raw_data.js.",
    "Report"
)

R = "'Raw Data'"  # sheet ref prefix
def rng(col):
    return f"{R}!{col}2:{col}{last_row}"

# ============================================================= TIER 1
t1 = wb.create_sheet("Tier1 - Headline")
t1.sheet_view.showGridLines = False

def section_title(ws, cell, text, size=14):
    ws[cell] = text
    ws[cell].font = Font(name=FONT, bold=True, size=size, color=navy)

def kpi_block(ws, top_row, left_col, label, formula, sub, numfmt="#,##0", value_color=navy):
    c = get_column_letter(left_col)
    c2 = get_column_letter(left_col + 1)
    ws.merge_cells(f"{c}{top_row}:{c2}{top_row}")
    ws[f"{c}{top_row}"] = label
    ws[f"{c}{top_row}"].font = Font(name=FONT, size=9, color="5C6864")
    ws.merge_cells(f"{c}{top_row+1}:{c2}{top_row+2}")
    ws[f"{c}{top_row+1}"] = formula
    ws[f"{c}{top_row+1}"].font = Font(name=FONT, bold=True, size=22, color=value_color)
    ws[f"{c}{top_row+1}"].number_format = numfmt
    ws.merge_cells(f"{c}{top_row+3}:{c2}{top_row+3}")
    ws[f"{c}{top_row+3}"] = sub
    ws[f"{c}{top_row+3}"].font = Font(name=FONT, size=8, italic=True, color="8B9793")
    for r in range(top_row, top_row + 4):
        for col in (left_col, left_col + 1):
            ws.cell(row=r, column=col).fill = PatternFill("solid", fgColor=grey_light)

section_title(t1, "B2", "Queue Flow — Headline Metrics")
t1["B3"] = "Scope: vaultServices where serviceFlow = \"queue\"  |  Launch: 24 Aug 2026  |  Report window: 24 Aug – 1 Sep 2026"
t1["B3"].font = Font(name=FONT, size=9, italic=True, color="5C6864")

row0 = 5
kpi_block(t1, row0, 2, "TOTAL CASES IN FLOW", f"=COUNTA({rng('A')})", "all serviceFlow=queue docs")
kpi_block(t1, row0, 4, "NEW CASES SINCE LAUNCH", f'=COUNTIF({rng("M")},"Yes")', "entered pipeline on/after 24 Aug")
kpi_block(t1, row0, 6, "ACTIVE PIPELINE SIZE", f'=SUMPRODUCT(({rng("H")}="open")*({rng("G")}<>"closed")*({rng("G")}<>"archived"))', "open, not closed or archived", value_color=teal)

row1 = row0 + 5
kpi_block(t1, row1, 2, "CLOSED SINCE LAUNCH", f'=COUNTIF({rng("P")},"Yes")', "of 1,010 total in flow", value_color="2F7D4F")
kpi_block(t1, row1, 4, "CLOSED, ALL-TIME (TAGGED)", f'=COUNTIF({rng("O")},"Yes")', "incl. pre-launch closures, tag backfilled")
kpi_block(t1, row1, 6, "SLA ADHERENCE (LAUNCH WINDOW)", f'=IFERROR(COUNTIFS({rng("P")},"Yes",{rng("S")},"Yes")/COUNTIF({rng("P")},"Yes"),"")', "closed at/before internal TAT target", numfmt="0.0%", value_color="B8791A")

row2 = row1 + 5
kpi_block(t1, row2, 2, "AVG END-TO-END TAT (DAYS)", f'=IFERROR(AVERAGEIFS({rng("Q")},{rng("P")},"Yes"),"")', "creation \u2192 closure, launch-window closures", numfmt="0.0")
kpi_block(t1, row2, 4, "REVENUE CLOSED SINCE LAUNCH", f'=SUMIFS({rng("U")},{rng("P")},"Yes")', "amount paid, INR", numfmt='"\u20b9"#,##0', value_color="2F7D4F")
kpi_block(t1, row2, 6, "REVENUE CLOSED, ALL-TIME", f'=SUMIFS({rng("U")},{rng("O")},"Yes")', "amount paid, INR, tagged cases", numfmt='"\u20b9"#,##0')

# Closed-by-day and new-by-day mini tables (for charting) below
row3 = row2 + 6
t1.cell(row=row3, column=2, value="New cases by day (since launch)").font = Font(name=FONT, bold=True, size=11)
t1.cell(row=row3+1, column=2, value="Date").font = Font(name=FONT, bold=True, size=9)
t1.cell(row=row3+1, column=3, value="New cases").font = Font(name=FONT, bold=True, size=9)
_launch_date = datetime.date(2026, 8, 24)
_today_date = datetime.date.today()
dates = [(_launch_date + datetime.timedelta(days=i)).isoformat()
         for i in range((_today_date - _launch_date).days + 1)]
for i, dt in enumerate(dates):
    r = row3 + 2 + i
    t1.cell(row=r, column=2, value=dt)
    t1.cell(row=r, column=3, value=f'=COUNTIFS({rng("L")},B{r},{rng("M")},"Yes")')

row4 = row3 + 2 + len(dates) + 1
t1.cell(row=row4, column=2, value="Closed cases by day (since launch)").font = Font(name=FONT, bold=True, size=11)
t1.cell(row=row4+1, column=2, value="Date").font = Font(name=FONT, bold=True, size=9)
t1.cell(row=row4+1, column=3, value="Closed cases").font = Font(name=FONT, bold=True, size=9)
for i, dt in enumerate(dates):
    r = row4 + 2 + i
    t1.cell(row=r, column=2, value=dt)
    t1.cell(row=r, column=3, value=f'=COUNTIFS({rng("N")},B{r},{rng("P")},"Yes")')

for r in range(row3+1, row4-1):
    t1.cell(row=r, column=2).font = Font(name=FONT, size=9)
    t1.cell(row=r, column=3).font = Font(name=FONT, size=9)
for r in range(row4+1, row4+2+len(dates)):
    t1.cell(row=r, column=2).font = Font(name=FONT, size=9)
    t1.cell(row=r, column=3).font = Font(name=FONT, size=9)

# charts
bar1 = BarChart()
bar1.title = "New cases entering flow, by day"
bar1.y_axis.title = "Cases"
bar1.style = 10
data = Reference(t1, min_col=3, min_row=row3+1, max_row=row3+1+len(dates))
cats = Reference(t1, min_col=2, min_row=row3+2, max_row=row3+1+len(dates))
bar1.add_data(data, titles_from_data=True)
bar1.set_categories(cats)
bar1.width, bar1.height = 15, 8
t1.add_chart(bar1, f"E{row3}")

bar2 = BarChart()
bar2.title = "Closed cases, by day"
bar2.y_axis.title = "Cases"
bar2.style = 11
data2 = Reference(t1, min_col=3, min_row=row4+1, max_row=row4+1+len(dates))
cats2 = Reference(t1, min_col=2, min_row=row4+2, max_row=row4+1+len(dates))
bar2.add_data(data2, titles_from_data=True)
bar2.set_categories(cats2)
bar2.width, bar2.height = 15, 8
t1.add_chart(bar2, f"E{row4}")

t1.column_dimensions["A"].width = 2
for col in "BCDEFGH":
    t1.column_dimensions[col].width = 15

# ============================================================= TIER 2 (aging x stage/substage — was "Tier2b", now the only Tier2 tab; the old
# "Tier2 - Pipeline Health" charts/breakdown tab was removed per user request, and this one renamed up to take its place)
stage_sub = [
    ("Doc", "To Validate"), ("Doc", "Incomplete"),
    ("Filing", "EC Applied"), ("Filing", "In Queue"), ("Filing", "EC Approved"), ("Filing", "In Process"),
    ("Applied", "Awaiting"), ("Applied", "Correction Required"), ("Applied", "Correction Applied"),
    ("Applied", "Approved"), ("Applied", "Submitted"),
    ("To Close", "Paid"), ("To Close", "Doc Shared"), ("To Close", "Approved"),
    ("qualified", ""), ("Ground", "E Stamp"),
]

t2b = wb.create_sheet("Tier2 - Aging by Stage")
t2b.sheet_view.showGridLines = False
section_title(t2b, "B2", "Aging of active pipeline — by stage/substage")
t2b["B3"] = "What stage each aging bucket's cases are actually stuck in. Rows = current stage/substage, columns = days since last touched."
t2b["B3"].font = Font(name=FONT, size=9, italic=True, color="5C6864")

r_cross_header = 6
cross_cols = ["0-1d", "1-3d", "3-7d", "7d+", "unknown"]
t2b.cell(row=r_cross_header, column=2, value="Stage").font = Font(name=FONT, bold=True, size=9, color=white)
t2b.cell(row=r_cross_header, column=2).fill = PatternFill("solid", fgColor=teal)
t2b.cell(row=r_cross_header, column=3, value="Substage").font = Font(name=FONT, bold=True, size=9, color=white)
t2b.cell(row=r_cross_header, column=3).fill = PatternFill("solid", fgColor=teal)
for j, cb in enumerate(cross_cols):
    c = t2b.cell(row=r_cross_header, column=4 + j, value=cb)
    c.font = Font(name=FONT, bold=True, size=9, color=white)
    c.fill = PatternFill("solid", fgColor=teal)
c_total = 4 + len(cross_cols)
t2b.cell(row=r_cross_header, column=c_total, value="Total").font = Font(name=FONT, bold=True, size=9, color=white)
t2b.cell(row=r_cross_header, column=c_total).fill = PatternFill("solid", fgColor=teal)

for i, (stage, sub) in enumerate(stage_sub):
    r = r_cross_header + 1 + i
    t2b.cell(row=r, column=2, value=stage).font = Font(name=FONT, size=9)
    sub_display = sub if sub else "(none)"
    t2b.cell(row=r, column=3, value=sub_display).font = Font(name=FONT, size=9)
    sub_criteria = f'IF(C{r}="(none)","",C{r})'
    for j, cb in enumerate(cross_cols):
        col = 4 + j
        t2b.cell(row=r, column=col,
                 value=f'=COUNTIFS({rng("I")},B{r},{rng("J")},{sub_criteria},{rng("AI")},"{cb}")').font = Font(name=FONT, size=9)
    total_letter_from = get_column_letter(4)
    total_letter_to = get_column_letter(4 + len(cross_cols) - 1)
    t2b.cell(row=r, column=c_total, value=f"=SUM({total_letter_from}{r}:{total_letter_to}{r})").font = Font(name=FONT, size=9, bold=True)
r_cross_end = r_cross_header + len(stage_sub)

# grand-total row, cross-checkable against Tier2's simple aging table
r_gt = r_cross_end + 1
t2b.cell(row=r_gt, column=2, value="TOTAL").font = Font(name=FONT, bold=True, size=9)
for j in range(len(cross_cols) + 1):
    col = 4 + j
    letter = get_column_letter(col)
    t2b.cell(row=r_gt, column=col, value=f"=SUM({letter}{r_cross_header+1}:{letter}{r_cross_end})").font = Font(name=FONT, bold=True, size=9)

t2b.column_dimensions["A"].width = 2
t2b.column_dimensions["B"].width = 14
t2b.column_dimensions["C"].width = 20
for col in "DEFGHI":
    t2b.column_dimensions[col].width = 11
t2b.freeze_panes = f"B{r_cross_header+1}"

# ============================================================= Today's-performance aggregates
# (Tier3, the old separate "Today" tab, Tier4, and the Orphaned Cases tab were all
# removed per user request — but these poc_today_df aggregates are still needed
# below by the Snapshot tab's "Today" KPI row, so the computation stays.)
poc_header = ["POC", "Filed", "hrs/case", "Revenue", "Rework", "Skipped", "Paused", "Reclaimed",
              "Not Connected", "Lost", "Blocked", "EC Filed", "Escalated Filed", "On-Time Closed",
              "Cases Closed", "On-Time %", "Break Time"]
poc_col_map = ["pocName", "filed", "hrsPerCase", "revenue", "rework", "skipped", "paused",
               "reclaimed", "notConnected", "lost", "blocked", "ecFiled", "escalatedFiled",
               "onTimeClosed", "caseClosedCount", "onTimePct", "breakTime"]
numeric_poc_cols = {"filed", "hrsPerCase", "revenue", "rework", "skipped", "paused", "reclaimed",
                    "notConnected", "lost", "blocked", "ecFiled", "escalatedFiled",
                    "onTimeClosed", "caseClosedCount", "onTimePct"}

today_filed = poc_today_df["filed"].astype(int).sum() if len(poc_today_df) else 0
today_revenue = poc_today_df["revenue"].astype(float).sum() if len(poc_today_df) else 0
today_closed = poc_today_df["caseClosedCount"].astype(int).sum() if len(poc_today_df) else 0
today_active_pocs = int((poc_today_df["filed"].astype(int) + poc_today_df["paused"].astype(int) +
                          poc_today_df["reclaimed"].astype(int) + poc_today_df["notConnected"].astype(int) > 0).sum()) if len(poc_today_df) else 0

# ============================================================= SNAPSHOT (single-page, easy-read)
snap = wb.create_sheet("Snapshot")
snap.sheet_view.showGridLines = False

snap["B2"] = "Queue Flow — Live Snapshot"
snap["B2"].font = Font(name=FONT, bold=True, size=18, color=navy)
snap["B3"] = f"Updated {BUILD_TIME_STR}  |  Flow live since 24 Aug 2026  |  All numbers verified against the CRM's own live data"
snap["B3"].font = Font(name=FONT, size=9, italic=True, color="5C6864")

thin = Side(style="thin", color="C4CDC9")
box = Border(top=thin, bottom=thin, left=thin, right=thin)

def big_tile(ws, row, col, label, formula, sub, numfmt="#,##0", color=navy):
    c = get_column_letter(col)
    c2 = get_column_letter(col + 1)
    ws.merge_cells(f"{c}{row}:{c2}{row}")
    ws[f"{c}{row}"] = label
    ws[f"{c}{row}"].font = Font(name=FONT, size=9, color="5C6864")
    ws.merge_cells(f"{c}{row+1}:{c2}{row+2}")
    ws[f"{c}{row+1}"] = formula
    ws[f"{c}{row+1}"].font = Font(name=FONT, bold=True, size=24, color=color)
    ws[f"{c}{row+1}"].number_format = numfmt
    ws.merge_cells(f"{c}{row+3}:{c2}{row+3}")
    ws[f"{c}{row+3}"] = sub
    ws[f"{c}{row+3}"].font = Font(name=FONT, size=8, italic=True, color="8B9793")
    for r in range(row, row + 4):
        for cc in (col, col + 1):
            ws.cell(row=r, column=cc).fill = PatternFill("solid", fgColor=grey_light)

def small_header(ws, row, col, labels, span=1):
    for i, lab in enumerate(labels):
        c = ws.cell(row=row, column=col + i, value=lab)
        c.font = Font(name=FONT, bold=True, size=9, color=white)
        c.fill = PatternFill("solid", fgColor=teal)
        c.border = box
        c.alignment = Alignment(horizontal="center" if i > 0 else "left", vertical="center")

def small_label(ws, row, col, text, bold=False):
    c = ws.cell(row=row, column=col, value=text)
    c.font = Font(name=FONT, bold=bold, size=9)
    c.fill = PatternFill("solid", fgColor=grey_light)
    c.border = box

def small_cell(ws, row, col, value, bold=False, numfmt="#,##0", center=True):
    c = ws.cell(row=row, column=col, value=value)
    c.font = Font(name=FONT, size=9, bold=bold)
    c.border = box
    c.number_format = numfmt
    if center:
        c.alignment = Alignment(horizontal="center")

# ---------------- Row of 6 headline KPIs ----------------
kpi_row = 6
big_tile(snap, kpi_row, 2, "TOTAL CASES IN FLOW", f"=COUNTA({rng('A')})", "since launch", color=navy)
big_tile(snap, kpi_row, 4, "ACTIVE PIPELINE", f'=SUMPRODUCT(({rng("H")}="open")*({rng("G")}<>"closed")*({rng("G")}<>"archived"))', "still open, not closed", color=navy)
big_tile(snap, kpi_row, 6, "WORKABLE RIGHT NOW", f'=COUNTIF({rng("AJ")},"Yes")', "needs a person's hand today", color=teal)
big_tile(snap, kpi_row, 8, "CLOSED SINCE LAUNCH", f'=COUNTIF({rng("P")},"Yes")', "8-day launch window", color="2F7D4F")
big_tile(snap, kpi_row, 10, "REVENUE COLLECTED", f'=SUMIFS({rng("U")},{rng("P")},"Yes")', "since launch, closed cases", numfmt='"₹"#,##0', color="2F7D4F")
big_tile(snap, kpi_row, 12, "SLA ADHERENCE", f'=IFERROR(COUNTIFS({rng("P")},"Yes",{rng("S")},"Yes")/COUNTIF({rng("P")},"Yes"),"")', "closed on/before TAT target", numfmt="0.0%", color="B8791A")

# ---------------- Today's performance (own row, refreshes daily) ----------------
today_row = kpi_row + 5
snap.cell(row=today_row - 1, column=2, value=f"Today — {datetime.date.today().strftime('%d %b %Y')} (IST)").font = Font(name=FONT, bold=True, size=13, color=navy)
big_tile(snap, today_row, 2, "FILED TODAY", int(today_filed), "cases moved to Applied today", color=teal)
big_tile(snap, today_row, 4, "REVENUE TODAY", float(today_revenue), "closed-case revenue, today", numfmt='"₹"#,##0', color="2F7D4F")
big_tile(snap, today_row, 6, "CLOSED TODAY", int(today_closed), "cases closed today", color="2F7D4F")
big_tile(snap, today_row, 8, "ACTIVE POCS TODAY", int(today_active_pocs), "logged at least one action today", color=navy)

# ---------------- Queue right now ----------------
r = today_row + 6
snap.cell(row=r, column=2, value="Queue right now — who's actually pickable").font = Font(name=FONT, bold=True, size=13, color=navy)
r += 1
snap.cell(row=r, column=2, value="\"Waiting\" = sitting in that team's queue. \"Available\" = waiting AND not paused AND not still snoozed/timed-out. Verified against the live CRM dashboard.").font = Font(name=FONT, size=8, italic=True, color="8B9793")
snap.merge_cells(start_row=r, start_column=2, end_row=r, end_column=6)
r += 1
qw_header_row = r
small_header(snap, r, 2, ["Team", "Waiting", "Available now", "% Available"])
r += 1
qw_data_start = r
for role in ["L0", "L1", "EC"]:
    avail, wait = qw_totals.get(role, (0, 0))
    small_label(snap, r, 2, role, bold=True)
    small_cell(snap, r, 3, wait)
    small_cell(snap, r, 4, avail, bold=True)
    pct = f"={get_column_letter(4)}{r}/{get_column_letter(3)}{r}" if wait else 0
    small_cell(snap, r, 5, pct, numfmt="0%")
    r += 1
qw_data_end = r - 1
r += 1

# ---------------- Pipeline funnel (true waterfall — each case counted ONCE,
# defined directly off live bucket/status/stage/queueBucket fields per the
# user's explicit spec (11 Sep 2026), not derived booleans. Precedence,
# highest first: Snoozed overrides every other tier below it (a paused or
# RNR case in ANY stage lands in "Snoozed", not its stage-based tier) >
# Service Completed > Doc Shared payment pending > Filed Waiting > Filed
# Approved > Correction cases > Pending for filing > remainder.) ----------------
snap.cell(row=r, column=2, value="Pipeline funnel — full breakdown of all cases in flow").font = Font(name=FONT, bold=True, size=13, color=navy)
r += 1
snap.cell(row=r, column=2, value="Old Lead = case existed before 24 Aug. New Lead = created on/after 24 Aug. Each case is counted once, in its single furthest-progressed stage (Snoozed overrides all other tiers) — rows sum exactly to Total Cases in Flow above.").font = Font(name=FONT, size=8, italic=True, color="8B9793")
r += 1
small_header(snap, r, 2, ["", "Old Leads", "New Leads", "Total"])
funnel_start = r + 1

def funnel_base_formula(lead_type, includes=None, include_or=None, pairs=None, exclude_snoozed=True):
    # SUMPRODUCT (not COUNTIFS) so an OR-within-one-column condition (e.g.
    # subStage is EITHER "Correction Required" OR "Correction Applied") can be
    # expressed as a single summed term — COUNTIFS can only AND criteria.
    # NOTE: deliberately NOT filtering on M ("entered pipeline since launch")
    # here — this funnel covers the FULL book (matches Total Cases in Flow),
    # split only by Old/New Lead (created before/after 24 Aug), not restricted
    # to cases that entered the pipeline since launch. Removed 15 Sep 2026
    # per explicit instruction: showing only the since-launch subset next to
    # the "Total Cases in Flow" headline was confusing, not clarifying.
    terms = [f'({rng("AK")}="{lead_type}")']
    for col, val in (includes or []):
        terms.append(f'({rng(col)}="{val}")')
    if include_or:
        col, vals = include_or
        or_term = "+".join([f'({rng(col)}="{v}")' for v in vals])
        terms.append(f"({or_term})")
    if pairs:
        # OR across whole (stage, substage) pairs, e.g. (Applied,Awaiting) OR
        # (Filing,EC Applied) — needed when the OR spans two different columns
        # at once, which include_or (single-column OR) can't express. Pairs
        # are mutually exclusive by construction (a case has one stage/substage),
        # so summing the AND'd terms is a safe OR with no double-counting.
        or_terms = []
        for conds in pairs:
            and_str = "*".join([f'({rng(c)}="{v}")' for c, v in conds])
            or_terms.append(f"({and_str})")
        terms.append("(" + "+".join(or_terms) + ")")
    if exclude_snoozed:
        # Snoozed (queueBucket="snoozed") overrides every other tier — a
        # paused/RNR case in Doc, Filing, or Applied/Correction Required all
        # land in "Snoozed" instead of their stage-based tier, per explicit
        # instruction: "if a case has queueBucket=snoozed, put it under
        # snoozed category only."
        terms.append(f'({rng("F")}<>"snoozed")')
    return "=SUMPRODUCT(" + "*".join(terms) + ")"

# (label, includes, include_or, pairs) — displayed in the order given, but
# Snoozed's exclusion is baked into every other tier via exclude_snoozed=True
# (the default), so precedence is enforced regardless of display order.
#
# "Filed, Waiting govt approval" and "Pending for filing" both used to match
# on stage alone (e.g. I="Filing", any substage), which silently swept
# Filing/EC Applied into "Pending for filing" — but EC Applied is a BBMP
# dependency (an external wait, exactly like Applied/Awaiting), not something
# a POC can act on, per the Active Stage Breakdown tab's own classification.
# Fixed 15 Sep 2026: EC Applied now counts under "Filed, Waiting govt
# approval" alongside Applied/Awaiting (with its own count shown in a bracket
# note beside that row — see ec_applied_note below), and "Pending for filing"
# is back to explicit workable pairs (which still includes EC Approved).
funnel_tiers = [
    ("Service Completed", [("G", "closed")], None, None),
    ("Doc Shared payment pending", [("G", "active"), ("I", "To Close"), ("J", "Doc Shared"), ("H", "open")], None, None),
    ("Filed, Waiting govt approval", [("G", "active"), ("H", "open")], None,
     [[("I", "Applied"), ("J", "Awaiting")], [("I", "Filing"), ("J", "EC Applied")]]),
    ("Filed, Govt. Approved", [("G", "active"), ("H", "open"), ("I", "Applied"), ("J", "Approved")], None, None),
    ("Correction cases", [("G", "active"), ("H", "open"), ("I", "Applied")], ("J", ["Correction Required", "Correction Applied"]), None),
    ("Pending for filing", [("G", "active"), ("H", "open")], None,
     [[("I", "Doc"), ("J", "To Validate")], [("I", "Filing"), ("J", "In Queue")], [("I", "Filing"), ("J", "In Process")], [("I", "Filing"), ("J", "EC Approved")]]),
    ("Snoozed", [("F", "snoozed")], None, None),
    ("Missing Documents", [("G", "pre active")], None, None),
    ("Moved to Blocked bucket", [("G", "blocked")], None, None),
]

funnel_defs_row = funnel_start
small_label(snap, funnel_defs_row, 2, "Into the new pipeline", bold=True)
# The base total must include EVERY case (snoozed ones too) — only the
# sub-tiers below apply the snoozed exclusion. Forgetting exclude_snoozed=False
# here previously shrank the total by every snoozed case while the Snoozed
# tier still counted them separately, producing a -2x(snoozed count) error.
# Plain COUNTIF, not SUMPRODUCT, for this single-condition base total —
# a bare single-term SUMPRODUCT was evaluating to 0 under the Excel COM
# recalculation engine used by recalc_excel.py, while structurally similar
# multi-term SUMPRODUCT formulas in the tier rows below computed correctly.
small_cell(snap, funnel_defs_row, 3, f'=COUNTIF({rng("AK")},"Old Lead")', bold=True)
small_cell(snap, funnel_defs_row, 4, f'=COUNTIF({rng("AK")},"New Lead")', bold=True)
small_cell(snap, funnel_defs_row, 5, f"={get_column_letter(3)}{funnel_defs_row}+{get_column_letter(4)}{funnel_defs_row}", bold=True)

tier_rows = []
for i, (label, includes, include_or, pairs) in enumerate(funnel_tiers):
    rr = funnel_defs_row + 1 + i
    tier_rows.append(rr)
    # The Snoozed tier itself must NOT exclude snoozed cases (that would zero
    # it out) — every other tier excludes them (exclude_snoozed defaults True).
    is_snoozed_tier = label == "Snoozed"
    small_label(snap, rr, 2, label)
    small_cell(snap, rr, 3, funnel_base_formula("Old Lead", includes, include_or, pairs, exclude_snoozed=not is_snoozed_tier))
    small_cell(snap, rr, 4, funnel_base_formula("New Lead", includes, include_or, pairs, exclude_snoozed=not is_snoozed_tier))
    small_cell(snap, rr, 5, f"={get_column_letter(3)}{rr}+{get_column_letter(4)}{rr}", bold=True)
    if label == "Filed, Waiting govt approval":
        # Bracket note: how many of this tier's total are Filing/EC Applied
        # specifically (both leads combined), so the merge with Applied/Awaiting
        # doesn't hide the EC-Applied count.
        ec_applied_formula = (
            f'=CONCATENATE("(of which ",'
            f'SUMPRODUCT(({rng("G")}="active")*({rng("H")}="open")*({rng("I")}="Filing")*({rng("J")}="EC Applied")*({rng("F")}<>"snoozed")),'
            f'" EC Applied)")'
        )
        small_cell(snap, rr, 6, ec_applied_formula, bold=False, numfmt="General", center=False)

# Remainder tier — cases that haven't reached ANY of the milestones above yet
# (e.g. still sitting in Doc/To Validate). Computed by subtraction, not another
# SUMPRODUCT, so it's guaranteed to reconcile exactly regardless of edge cases.
remainder_row = funnel_defs_row + 1 + len(funnel_tiers)
small_label(snap, remainder_row, 2, "Not yet at any milestone")
for col in (3, 4):
    letter = get_column_letter(col)
    tier_refs = "+".join([f"{letter}{rr}" for rr in tier_rows])
    small_cell(snap, remainder_row, col, f"={letter}{funnel_defs_row}-({tier_refs})")
small_cell(snap, remainder_row, 5, f"={get_column_letter(3)}{remainder_row}+{get_column_letter(4)}{remainder_row}", bold=True)

# Sanity-check row. NOTE: "remainder == total - sum(tiers)" is a tautology by
# construction (remainder_row's OWN formula is that subtraction), so checking
# "tiers + remainder == total" would always read OK even when the 7 real
# tiers double-count each other — that exact blind spot let a real bug (base
# total wrongly excluding snoozed cases, caught 11 Sep 2026) through silently.
# The genuine, non-trivial check is that the 7 real tiers alone don't exceed
# the total (remainder >= 0) — that's what actually catches double-counting.
check_row = remainder_row + 1
small_label(snap, check_row, 2, "Check: no tier double-counting? (remainder >= 0)", bold=False)
snap.cell(row=check_row, column=2).font = Font(name=FONT, size=8, italic=True, color="8B9793")
for col in (3, 4, 5):
    letter = get_column_letter(col)
    c = snap.cell(row=check_row, column=col, value=f'=IF({letter}{remainder_row}>=0,"OK","MISMATCH")')
    c.font = Font(name=FONT, size=9, italic=True, color="8B9793")
    c.border = box

funnel_end = check_row

# ---------------- Top POCs by cases filed (verified leaderboard) ----------------
r2 = qw_header_row
c2 = 8
snap.cell(row=r2, column=c2, value="Top POCs — filed since launch (verified)").font = Font(name=FONT, bold=True, size=13, color=navy)
r2 += 1
snap.cell(row=r2, column=c2, value="Straight from the CRM's own activity log — matches the in-app leaderboard exactly.").font = Font(name=FONT, size=8, italic=True, color="8B9793")
r2 += 1
small_header(snap, r2, c2, ["POC", "Filed", "Paused", "Revenue"])
r2 += 1
poc_sorted = poc_df.copy()
poc_sorted["filed_n"] = poc_sorted["filed"].astype(int)
poc_sorted = poc_sorted.sort_values("filed_n", ascending=False)
top_pocs = poc_sorted[poc_sorted["filed_n"] > 0].head(10)
poc_top_start = r2
for _, row in top_pocs.iterrows():
    small_label(snap, r2, c2, row["pocName"])
    small_cell(snap, r2, c2 + 1, int(row["filed"]), bold=True)
    small_cell(snap, r2, c2 + 2, int(row["paused"]))
    small_cell(snap, r2, c2 + 3, int(row["revenue"]), numfmt='"₹"#,##0')
    r2 += 1
poc_top_end = r2 - 1
r2 += 1

# ---------------- Pending for Filing aging ----------------
r3 = max(funnel_end, poc_top_end) + 3
snap.cell(row=r3, column=2, value="Pending for Filing — how long they've waited").font = Font(name=FONT, bold=True, size=13, color=navy)
r3 += 1
small_header(snap, r3, 2, ["Days waiting", "Old Leads", "New Leads", "Total"])
aging_defs = [
    ("0 day", 0, 1),
    ("1 day", 1, 2),
    ("2-3 days", 2, 4),
    ("3-5 days", 4, 6),
    ("5+ days", 6, None),
]
aging_start = r3 + 1
for i, (label, lo, hi) in enumerate(aging_defs):
    rr = aging_start + i
    small_label(snap, rr, 2, label)
    for j, lead in enumerate(["Old Lead", "New Lead"]):
        col = 3 + j
        if hi is None:
            cond = f'{rng("AP")},">={lo}"'
        else:
            cond = f'{rng("AP")},">={lo}",{rng("AP")},"<{hi}"'
        formula = f'=COUNTIFS({rng("M")},"Yes",{rng("AN")},"Yes",{rng("AK")},"{lead}",{cond})'
        small_cell(snap, rr, col, formula)
    small_cell(snap, rr, 5, f"={get_column_letter(3)}{rr}+{get_column_letter(4)}{rr}", bold=True)
rr_unknown = aging_start + len(aging_defs)
small_label(snap, rr_unknown, 2, "Unknown / no timestamp")
for j, lead in enumerate(["Old Lead", "New Lead"]):
    col = 3 + j
    formula = f'=COUNTIFS({rng("M")},"Yes",{rng("AN")},"Yes",{rng("AK")},"{lead}",{rng("AQ")},"unknown")'
    small_cell(snap, rr_unknown, col, formula)
small_cell(snap, rr_unknown, 5, f"={get_column_letter(3)}{rr_unknown}+{get_column_letter(4)}{rr_unknown}", bold=True)
rr_total = rr_unknown + 1
small_label(snap, rr_total, 2, "Total", bold=True)
for col in (3, 4, 5):
    letter = get_column_letter(col)
    small_cell(snap, rr_total, col, f"=SUM({letter}{aging_start}:{letter}{rr_unknown})", bold=True)
aging_end = rr_total

# ---------------- Pause reasons (compact) ----------------
# Categorized from the REAL free-text note content (pausedReasonDetail) and
# dependency metadata (pauseDependencyServiceId, pauseDueToDependency), not
# the vague dropdown value (currentPauseReason — often just "Other" or blank,
# which is why the old version of this table was wrong: it made a large chunk
# of paused cases look undocumented when the real notes explain nearly all of
# them). Regex categorization isn't expressible as a live Excel formula, so
# these are computed here in Python and written as static values — same
# taxonomy already validated against the Paused cases tab earlier this session.
import re as _re

def categorize_pause_reason(row):
    text = str(row.get("pausedReasonDetail", "") or "").lower()
    if str(row.get("pauseDueToDependency", "")) == "Yes" or row.get("pauseDependencyServiceId"):
        return "Dependency on another case/service"
    if not text:
        return "Genuinely undocumented"
    if _re.search(r"otp|not (giving|share|cooperat)", text):
        return "Customer non-cooperation (OTP/verification refusal)"
    if _re.search(r"unavailable|not (picking|answering|responding|there)|disconnect|out of (country|town|station)|wife is not there|will come back|hold (the )?correction|hold for", text):
        return "Customer unavailable / requested hold"
    if "refund" in text:
        return "Refund case (should likely be closed, not paused)"
    if _re.search(r"not willing to accept|proceed with closing", text):
        return "Dispute — flagged for closure"
    if _re.search(r"portal.*(already|glitch|showing|not working|not visible)|glitch", text):
        return "BBMP portal issue or glitch"
    if _re.search(r"grievance|complaint", text):
        return "Grievance/complaint raised"
    if _re.search(r"family tree|document.*(not received|missing)|docs? not", text):
        return "Missing documents from customer"
    if _re.search(r"forest department|legal team|objection", text):
        return "Government/legal objection"
    if _re.search(r"bescom bill|bill.*already used|wrong (bescom )?bill|incorrect bill", text):
        return "Document/data conflict (e.g. bill reused/incorrect)"
    if _re.search(r"society|site visit|resident|builders name", text):
        return "Site/society/builder-level issue"
    if _re.search(r"deadline|missed|unable to arrange", text):
        return "Missed external deadline"
    return "Other (documented, uncategorized)"

paused_cohort = df[(df["isNewSinceLaunch"] == "Yes") & (df["pausedNow"] == "Yes")].copy()
paused_cohort["category"] = paused_cohort.apply(categorize_pause_reason, axis=1)
reason_counts = paused_cohort["category"].value_counts().sort_values(ascending=False)

r4 = qw_header_row
c4 = 13
snap.cell(row=r4, column=c4, value="Why cases are paused (this cohort)").font = Font(name=FONT, bold=True, size=13, color=navy)
r4 += 1
snap.cell(row=r4, column=c4, value="Categorized from real note text + dependency links, not the raw dropdown reason.").font = Font(name=FONT, size=8, italic=True, color="8B9793")
r4 += 1
small_header(snap, r4, c4, ["Reason", "Cases"])
r4 += 1
reason_start = r4
for reason, count in reason_counts.items():
    small_label(snap, r4, c4, reason)
    small_cell(snap, r4, c4 + 1, int(count))
    r4 += 1
reason_end = r4 - 1

bottom_row = max(aging_end, reason_end) + 2
snap.cell(row=bottom_row, column=2, value="Full case-level detail: Raw Data tab.  Aging by stage/substage: Tier2 - Aging by Stage tab.").font = Font(name=FONT, size=8, italic=True, color="8B9793")
snap.merge_cells(start_row=bottom_row, start_column=2, end_row=bottom_row, end_column=8)

snap.column_dimensions["A"].width = 2
snap.column_dimensions["B"].width = 24
for col in "CDEFG":
    snap.column_dimensions[col].width = 13
snap.column_dimensions["H"].width = 20
for col in "IJK":
    snap.column_dimensions[col].width = 13
snap.column_dimensions["L"].width = 3
snap.column_dimensions["M"].width = 26
snap.column_dimensions["N"].width = 10
# ============================================================= sheet order
wb.move_sheet("Snapshot", offset=-(len(wb.sheetnames) - 1))
wb.move_sheet("Raw Data", offset=len(wb.sheetnames) - 1)
wb.active = 0

wb.save(OUT_XLSX)
print(f"Saved workbook to {OUT_XLSX}")
